[package]
name = "khulnasoft-wrappers"
version = "0.1.17"
edition = "2021"
authors = ["Khulnasoft Inc. https://khulnasoft.com/"]
license = "Apache-2.0"
description = "Postgres Foreign Data Wrapper development framework in Rust."
homepage = "https://github.com/khulnasoft/wrappers/tree/main/khulnasoft-wrappers"
repository = "https://github.com/khulnasoft/wrappers/tree/main/khulnasoft-wrappers"
categories = ["database"]
keywords = ["database", "postgres", "postgresql", "extension"]

[features]
default = ["cshim", "pg15"]
cshim = ["pgrx/cshim"]
pg14 = ["pgrx/pg14", "pgrx-tests/pg14"]
pg15 = ["pgrx/pg15", "pgrx-tests/pg15"]
pg16 = ["pgrx/pg16", "pgrx-tests/pg16"]
pg_test = []

[dependencies]
pgrx = { version = "=0.11.3", default-features = false }
thiserror = "1.0.48"
tokio = { version = "1.35", features = ["rt", "net"] }
uuid = { version = "1.2.2" }
khulnasoft-wrappers-macros = { version = "0.1", path = "../khulnasoft-wrappers-macros" }

[dev-dependencies]
pgrx-tests = "=0.11.3"

[package.metadata.docs.rs]
features = ["pg15", "cshim"]
no-default-features = true
# Enable `#[cfg(docsrs)]` (https://docs.rs/about/builds#cross-compiling)
rustc-args = ["--cfg", "docsrs"]
